[workspace]
resolver = "2"
members = ["crates/mx", "crates/cli", "crates/tree-sitter-mx"]

[workspace.dependencies]
streaming-iterator = "0.1.9"
tree-sitter = "0.24.0"
tree-sitter-mx = { path = "crates/tree-sitter-mx" }
