[package]
name = "mx"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.0"

[dependencies]
streaming-iterator = "0.1.9"
tokio = { version = "1", features = ["full"] }
tower-lsp = "0.20.0"
tree-sitter = "0.24.7"
tree-sitter-mx = { path = "tree-sitter-mx" }
