[package]
name = "mx-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mx"
path = "src/main.rs"

[dependencies]
streaming-iterator.workspace = true
tokio = { version = "1", features = ["full"] }
tower-lsp = "0.20.0"
mx = { path = "../mx" }
