[package]
name = "mx"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
cc = "1.0"

[dependencies]
streaming-iterator.workspace = true
tree-sitter.workspace = true
tree-sitter-mx.workspace = true
